//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Domain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ActionType {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActionType() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.Domain.ActionType", typeof(ActionType).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action type.
        /// </summary>
        public static string Action_Type {
            get {
                return ResourceManager.GetString("Action Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All roles.
        /// </summary>
        public static string All_roles {
            get {
                return ResourceManager.GetString("All roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users.
        /// </summary>
        public static string All_Users {
            get {
                return ResourceManager.GetString("All Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign role.
        /// </summary>
        public static string Assign_role {
            get {
                return ResourceManager.GetString("Assign role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign role to user.
        /// </summary>
        public static string Assign_role_to_user {
            get {
                return ResourceManager.GetString("Assign role to user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Change_password {
            get {
                return ResourceManager.GetString("Change password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string Confirm_new_password {
            get {
                return ResourceManager.GetString("Confirm new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new current stock.
        /// </summary>
        public static string Create_new_current_stock {
            get {
                return ResourceManager.GetString("Create new current stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create role.
        /// </summary>
        public static string Create_role {
            get {
                return ResourceManager.GetString("Create role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Current_password {
            get {
                return ResourceManager.GetString("Current password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current stock.
        /// </summary>
        public static string Current_Stock {
            get {
                return ResourceManager.GetString("Current Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string Edit_Profile {
            get {
                return ResourceManager.GetString("Edit Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter current password.
        /// </summary>
        public static string Enter_current_password {
            get {
                return ResourceManager.GetString("Enter current password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new password.
        /// </summary>
        public static string Enter_new_password {
            get {
                return ResourceManager.GetString("Enter new password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string Enter_your_email {
            get {
                return ResourceManager.GetString("Enter your email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by status.
        /// </summary>
        public static string Filter_By_Status {
            get {
                return ResourceManager.GetString("Filter By Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to firstname.
        /// </summary>
        public static string Firsname {
            get {
                return ResourceManager.GetString("Firsname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname.
        /// </summary>
        public static string Firstname {
            get {
                return ResourceManager.GetString("Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string Full_name {
            get {
                return ResourceManager.GetString("Full name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get role.
        /// </summary>
        public static string Get_role {
            get {
                return ResourceManager.GetString("Get role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventories.
        /// </summary>
        public static string Inventories {
            get {
                return ResourceManager.GetString("Inventories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname.
        /// </summary>
        public static string Lastname {
            get {
                return ResourceManager.GetString("Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low stock alert.
        /// </summary>
        public static string Low_Stock_Alert {
            get {
                return ResourceManager.GetString("Low Stock Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most active removers.
        /// </summary>
        public static string Most_Active_Removers {
            get {
                return ResourceManager.GetString("Most Active Removers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most removed products.
        /// </summary>
        public static string Most_Removed_Products {
            get {
                return ResourceManager.GetString("Most Removed Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string My_account {
            get {
                return ResourceManager.GetString("My account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New action.
        /// </summary>
        public static string New_Action {
            get {
                return ResourceManager.GetString("New Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string New_password {
            get {
                return ResourceManager.GetString("New password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        public static string No_data_found {
            get {
                return ResourceManager.GetString("No data found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match.
        /// </summary>
        public static string No_match {
            get {
                return ResourceManager.GetString("No match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pending actions.
        /// </summary>
        public static string No_pending_actions {
            get {
                return ResourceManager.GetString("No pending actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No problematic products found.
        /// </summary>
        public static string No_problematic_products_found {
            get {
                return ResourceManager.GetString("No problematic products found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No users found.
        /// </summary>
        public static string No_users_found {
            get {
                return ResourceManager.GetString("No users found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending actions.
        /// </summary>
        public static string Pending_Actions {
            get {
                return ResourceManager.GetString("Pending Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product code.
        /// </summary>
        public static string Product_Code {
            get {
                return ResourceManager.GetString("Product Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick product search.
        /// </summary>
        public static string Quick_Product_Search {
            get {
                return ResourceManager.GetString("Quick Product Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save data.
        /// </summary>
        public static string Save_data {
            get {
                return ResourceManager.GetString("Save data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by code.
        /// </summary>
        public static string Search_by_code {
            get {
                return ResourceManager.GetString("Search by code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name.
        /// </summary>
        public static string Search_by_name {
            get {
                return ResourceManager.GetString("Search by name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by name or code.
        /// </summary>
        public static string Search_by_name_or_code {
            get {
                return ResourceManager.GetString("Search by name or code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an inventory to see total worth.
        /// </summary>
        public static string Select_an_inventory_to_see_total_worth {
            get {
                return ResourceManager.GetString("Select an inventory to see total worth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select inventory.
        /// </summary>
        public static string Select_Inventory {
            get {
                return ResourceManager.GetString("Select Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select role.
        /// </summary>
        public static string Select_role {
            get {
                return ResourceManager.GetString("Select role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock.
        /// </summary>
        public static string Stock {
            get {
                return ResourceManager.GetString("Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock data not available.
        /// </summary>
        public static string Stock_data_not_available {
            get {
                return ResourceManager.GetString("Stock data not available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage rooms.
        /// </summary>
        public static string Storage_Rooms {
            get {
                return ResourceManager.GetString("Storage Rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage room.
        /// </summary>
        public static string StorageRoom {
            get {
                return ResourceManager.GetString("StorageRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone number.
        /// </summary>
        public static string Telephone_nr {
            get {
                return ResourceManager.GetString("Telephone nr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User and roles.
        /// </summary>
        public static string Users_and_roles {
            get {
                return ResourceManager.GetString("Users and roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        public static string View_All {
            get {
                return ResourceManager.GetString("View All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View current stock.
        /// </summary>
        public static string View_Current_Stock {
            get {
                return ResourceManager.GetString("View Current Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Storage Rooms.
        /// </summary>
        public static string View_Storage_Rooms {
            get {
                return ResourceManager.GetString("View Storage Rooms", resourceCulture);
            }
        }
    }
}
